### PR TITLE
Memory pair

### PR DESCRIPTION
**Pull request by AnnaStoyano**
### Memory – Pair Game

[Demo](https://annastoyano.github.io/memory-pair/index.html) |
[Code base](https://github.com/AnnaStoyano/memory-pair)

Please, review.

### CODE REVIEW

**Comment by AMashoshyna** [comment]
Hi @AnnaStoyano! Looks like you have code for two separate tasks in one PR. Please keep the saparate

**Comment by AnnaStoyano** [comment]
Hi @AMashoshyna) Please can you give me advice how can I solve this problem? I created new branch for memory-pair game and made commit. After that I pull from upstream to main, switch branch to memory-pair and merge main. Than I push my branch and create new Pull request.

**Comment by AMashoshyna** [comment]
@AnnaStoyano my theory is that you might have forgotten to switch branch to `main` before creating memory-pair game branch. Thus you memory-pair game includes commits from frogger branch.

What we have now:
latest commit in main => frogger commits  (HEAD of frogger branch) => memory-pair game commit (HEAD of memory-pair game branch)

What we want:

latest commit in main => frogger commits  (HEAD of frogger branch)
latest commit in main => memory-pair game commit (HEAD of memory-pair game branch)

I see that memory-pair game has only one commit so far, so I would checkout main, create new branch for memory pair game task, cherry-pick this commit with memory pair game and open a new PR.

**Comment by AnnaStoyano** [comment]
@AMashoshyna  thank you very much! Your advice helps me.

**Comment by AnnaStoyano** [comment]
I create new PR

**Pull request closed without merging**
