### PR TITLE
dom-api-task

### PR DESCRIPTION
**Pull request by t-jay-777**
### Document Object Model

[Demo](https://t-jay-777.github.io/dom/)
[Code base](https://github.com/t-jay-777/frontend-2021-homeworks/tree/main/submissions/t-jay-777/dom-api-task)

The code is submitted in a dedicated feature branch.
Please, review.

### CODE REVIEW

**Review by OleksiyRudenko — CHANGES_REQUESTED** [review]
@t-jay-777 thank you for your submission.
However there are few issues.

1. The PR contains files from a different task
image

2. The PR adds a file to another student's directory
image

3. Code base link should lead to the app's original repo, not to this repo.

4. Images are not required for review. But loading them takes time from other students. Please do add only the files that can be reviewed (`css`, `html`, `js` and alike)

**Comment by OleksiyRudenko** [comment]
Feel free seeking for an advice in the course chat.

**Comment by OleksiyRudenko** [comment]
I believe some of the issues above happen just beacuse you commited locally to `main` instead of having a dedicated branches for your tasks.

**Comment by OleksiyRudenko** [comment]
Cannot find any PR that would offer **html css popup**. You may want to submit some of your files as such.

**Comment by t-jay-777** [comment]
> Cannot find any PR that would offer **html css popup**. You may want to submit some of your files as such.

I guess it is because I add my  popup task to 
**frontend-2021-homeworks** from previous **
frontend-2019-homeworks** in the beginning

**Comment by OleksiyRudenko** [comment]
Let's have [it linked here](https://github.com/kottans/frontend-2019-p2p/pull/128) for history tracking purposes

**Comment by t-jay-777** [comment]
> Images are not required for review. But loading them takes time from other students. Please do add only the files that can be reviewed (css, html, js and alike)

I changed urls for images so they are in web storage.

> The PR contains files from a different task

As I mentioned before I add my previous popup task to repo 2021.

> The PR adds a file to another student's directory

I don't know the reason. This commit usually hanged as uncommited changes before I did push of my repo.

> I believe some of the issues above happen just beacuse you commited locally to main instead of having a dedicated branches for your tasks.

I used `git push` instead of `git push --set-upstream origin dom-api-task`

> Cannot find any PR that would offer html css popup. You may want to submit some of your files as such.

[here you go](https://github.com/kottans/frontend-2019-p2p/pull/128#issue-358381260)

**Comment by OleksiyRudenko** [comment]
We need to fix this PR.
The core cause is that the code should have been committed to a dedicated branch, not to `main`.
[Here](https://gist.github.com/OleksiyRudenko/8b3ddb664308de0634b53c525e551d8b) you will find the problem description (among other similar) and solution.
Please feel free asking for help in the student's chat. You will find there many people willing to help.
Unfortunately my top priority now is review of pending PRs for other tasks.

**Pull request closed without merging**
