### PR TITLE
implement memory game

### PR DESCRIPTION
**Pull request by akulahere**
### Memory game

[Demo](https://akulahere.github.io/memory-game/)
[Code base](https://github.com/akulahere/memory-game)

The code is submitted in a dedicated feature branch.
Please, review.

### CODE REVIEW

**Review by babayK0 — CHANGES_REQUESTED** [review]
Good job! 
But let improve your code:
1. I can play game before downloading of images. fix this please.
1. Why not generate cards with js ?) 
1. watch my comments below

**Comment by OleksiyRudenko** [comment]
@akulahere Please let us know until 20:00 today if you are going to submit any changes into this PR before end of the day February 27. This would help us to plan mentors' limited capacity accordingly.

**Comment by akulahere** [comment]
@OleksiyRudenko I plan to fix all requests until workday today.

**Comment by akulahere** [comment]
Done

**Comment by akulahere** [comment]
Miss point 1 and 2 in your previous comment. Will fix it soon.

**Comment by akulahere** [comment]
1. Fix with load listen on window.
2. I prefer to avoid add html code in js if it is not necessary. In this case I think it's better to understand layout, when I not generate it with js.

**Review by babayK0 — APPROVED** [review]
:+1:

**Pull request merged**
