### PR TITLE
Object-Oriented JavaScript - practice

### PR DESCRIPTION
**Pull request by Iakow**
### Object-Oriented JavaScript - practice 

[Demo](https://iakow.github.io/frontend-nanodegree-arcade-game/) |
[Code base](https://github.com/Iakow/frontend-2021-homeworks/blob/oop-js-frogger/submissions/iakow/object-oriented-js/app.js)

The code is submitted in a dedicated feature branch.
Please, review.

### CODE REVIEW

**Comment by OleksiyRudenko** [comment]
@Iakow nice touch-up with sounds! :)
While we're looking for some review capacity please feel free checking your code against the following list of requirements.

# Frogger Arcade Game -- JS OO exercise check list

A self-check list. Relates to
[Object-Oriented JavaScript](https://github.com/kottans/frontend/blob/master/tasks/js-oop.md) task.

## Check-list

Minimal requirements to meet:
 * [ ] it is OK to employ ES6 features like `const`, `let` etc.
 * [ ] OO is implemented using JS prototype chain object model (**not** ES6 classes syntax)
 * Requirements re **Constants**:
   * [ ] all numbers like block dimensions, initial locations are defined as constants
   * [ ] there are core constants and derived constants
         (e.g. `const FIELD_WIDTH = BLOCK_WIDTH * BLOCKS_NUMBER;`)
   * [ ] arrays of constants are also constants 
         (e.g. `const INITIAL_POSITIONS = [1,2,3,4].map(rowNumber => rowNumber * BLOCK_HEIGHT);`)
   * [ ] const objects help organizing and structure const data even better
         (e.g. `const PLAYER_CONF = { initialPosition: {x: 1, y: 5}, sprite: '...', ...etc... };`
 * Requirements re **OOP**:
   * [ ] properties common for some classes are generalized into a base class
         (e.g. there is `Character` base class, which is extended by `Enemy` and `Player` classes)
   * [ ] class extension is implemented using `Subclass.prototype = Object.create(Superclass.prototype)`,
         not `Subclass.prototype = new Superclass(params);`;
         [Useful resource](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Inheritance_and_the_prototype_chain)
   * [ ] classes do not refer to any global variables, like global variable `player`, which is an instance of `Player` class
         (referring to global constants and globals provided by the gaming platform like `Resources` is OK);
         Hint: pass `Player` instance as an argument to every enemy
   * [ ] Separation of Concerns principle is followed
         (e.g. `update` method does only rendering and 
         doesn't **contain** any inline code to check e.g. collisions)
   * [ ] the code is very [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself)

Please, confirm all items above are positive. Please, ask a question if anything above requires clarification.

**Comment by Iakow** [comment]
Hello!

**Comment by Iakow** [comment]
I think I brought the code in accordance with the checklist.
Fell down the rabbit hole with all these `this` and prototype chains ))
I've tried a ton of ways to write this code, and I think I've chosen the best option.
I'm not capable of more))

**Review by OleksiyRudenko — APPROVED** [review]
@Iakow good job!
There are still mysterious numbers across the code base with not really clear semantic purpose.
At all times keep thinking how the code **reads**. The closer to plain English the better.

**Pull request merged**
