### PR TITLE
Hooli-style-Popup-fix-bug

### PR DESCRIPTION
**Pull request by SkirnevskyiAleksandr**
### Hooli-style-Popup

[Demo](https://skirnevskyialeksandr.github.io/Hooli-style-Popup/)
[Code base](https://github.com/SkirnevskyiAleksandr/Hooli-style-Popup)

The code is submitted in a dedicated feature branch.
Please, review.

### CODE REVIEW

**Comment by babayK0** [comment]
Please rename pr

**Comment by SkirnevskyiAleksandr** [comment]
> Please rename pr
Hello! thanks  for the answer! If you mean rename "pull request", It`s done.

**Review by lenadgit — CHANGES_REQUESTED** [review]
Could you please add your fixes to your previous Pull Request? https://github.com/kottans/frontend-2021-homeworks/pull/239
Why did you open this PR with fixes for the previous? Do you have any problems with the previous one?

**Comment by SkirnevskyiAleksandr** [comment]
Good night! Yes, i'm a little confused with the first pool quest (but i think i fixed it). Тow i cancel this pool quest and leave the first one. My apologies)!

**Pull request closed without merging**
