### PR TITLE
Pre oop task

### PR DESCRIPTION
**Pull request by alstep07**
### JS pre-oop

[Demo](https://alstep07.github.io/a-tiny-JS-world/) |
[Code base](https://github.com/alstep07/a-tiny-JS-world/blob/populate-world/index.js)

The code is submitted in a dedicated feature branch.
Please, review.

### CODE REVIEW

**Comment by OleksiyRudenko** [comment]
Your PR [suggests files](https://github.com/kottans/frontend-2021-homeworks/pull/247/files) from a different task.
Can you please check and fix?

**Comment by alstep07** [comment]
> Your PR [suggests files](https://github.com/kottans/frontend-2021-homeworks/pull/247/files) from a different task.
> Can you please check and fix?

Thank you! I will ask for help in questionarium and then fix it.

**Comment by alstep07** [comment]
> Your PR [suggests files](https://github.com/kottans/frontend-2021-homeworks/pull/247/files) from a different task.
> Can you please check and fix?

Fix it!

**Comment by OleksiyRudenko** [comment]
The screenshot below shows emulation of the following process:
1. Your #245 gets merged. This will add `submissions/alstep07/task_js_dom/*`
2. This your PR gets merged. This will add `submissions/alstep07/tiny-js-world/*` and remove `submissions/alstep07/task_js_dom/*`

image

We do not want any submissions being removed.

**Pull request closed without merging**
