### PR TITLE
Init commit of friends app

### PR DESCRIPTION
**Pull request by Lu-sure**
### Friends app

[Demo](https://lu-sure.github.io/Friends_app/)
[Code base](https://github.com/Lu-sure/Lu-sure.github.io/tree/main/Friends_app)

The code is submitted in a dedicated feature branch.
Please, review.

### CODE REVIEW

**Review by A-Ostrovnyy — CHANGES_REQUESTED** [review]
Good work!
See my comments below!

**Comment by OleksiyRudenko** [comment]
@Lu-sure Please let us know until 20:00 today if you are going to submit any changes into this PR before end of the day February 27. This would help us to plan mentors' limited capacity accordingly.

**Comment by Lu-sure** [comment]
@OleksiyRudenko, I'm not going to submit any changes into this PR before end of the day February 27, apart from the one, I made today early. Than you for your mentor work)

**Review by A-Ostrovnyy — APPROVED** [review]
LGTM
Well done!

**Pull request merged**
