### PR TITLE
Add folder (one more time) with new js-dom task and old popup-task, c…

### PR DESCRIPTION
**Pull request by AndriiZahumnyi**
…ause my folder was absent.

### JS-DOM

[Demo](https://andriizahumnyi.github.io/DOM---Practical-Task/) |
[Code base](https://github.com/AndriiZahumnyi/DOM---Practical-Task)

The code is submitted in a dedicated feature branch.
Please, review.

### CODE REVIEW

**Comment by OleksiyRudenko** [comment]
Please have one PR per one task. Just imagine what a mess would be the review of unrelated code bases. Besides if one of the tasks is OK its merging will be blocked by the other one incomplete review, and we might easily miss the moment when both are ok.

**Comment by AndriiZahumnyi** [comment]
> Please have one PR per one task. Just imagine what a mess would be the review of unrelated code bases. Besides if one of the tasks is OK its merging will be blocked by the other one incomplete review, and we might easily miss the moment when both are ok.

OK!
But my popup task and my folder AndriiZahumnyi just weren`t!!
Somobody remowed them or I even don`t know what happend...

**Comment by AndriiZahumnyi** [comment]
> Please have one PR per one task. Just imagine what a mess would be the review of unrelated code bases. Besides if one of the tasks is OK its merging will be blocked by the other one incomplete review, and we might easily miss the moment when both are ok.
Her`s my merged earlier PR, but now is not my folder and is not my Popup task...
https://github.com/kottans/frontend-2021-homeworks/pull/116

**Comment by OleksiyRudenko** [comment]
I still can see you popup code in the codebase.
image

Update your local master from the upstream to have your fork code base updated.

**Comment by OleksiyRudenko** [comment]
> > Please have one PR per one task. Just imagine what a mess would be the review of unrelated code bases. Besides if one of the tasks is OK its merging will be blocked by the other one incomplete review, and we might easily miss the moment when both are ok.
> > Her`s my merged earlier PR, but now is not my folder and is not my Popup task...
> > #116

I see. Let me take a look into it

**Comment by AndriiZahumnyi** [comment]
> I still can see you popup code in the codebase.
> image
> 
> Update your local master from the upstream to have your fork code base updated.

Ok!
I will try, it seems to me that I get old branch...
Thank you.

**Comment by OleksiyRudenko** [comment]
> but now is not my folder and is not my Popup task...

Well, commits to the both of the files are authored by you according to the git history.

image

image

**Comment by AndriiZahumnyi** [comment]
> > but now is not my folder and is not my Popup task...
> 
> Well, commits to the both of the files are authored by you according to the git history.
> 
> image
> 
> image

Oleksiy!
Could I make new PR from another my new branch with correct updating, that I already have  and delete this PR, because i can`t, so quickly, update this branch. I tried to update this one and made it but not so good, not so clean, like new PR.

**Comment by OleksiyRudenko** [comment]
@AndriiZahumnyi if this PR was merged it would make files from your other submission deleted
image

**Comment by AndriiZahumnyi** [comment]
I have some problems with this second PR and it`s like a joke, but I understand that I just make some mistakes.... the whole day, till 7 o`clock...

> @AndriiZahumnyi if this PR was merged it would make files from your other submission deleted
> image

I have some problems with this second PR and it`s like a joke, but I understand that I just make some mistakes.... the whole day, from 7 o`clock...

**Comment by OleksiyRudenko** [comment]
Let's re-try:

1. `git checkout main`
2. Check if there are any files from JS Dom task. If there are any then halt and tell me, there shouldn't be any. We'd need then to normalize your repo first.
2. `git pull upstream`
3. `git branch -b js-dom-task` (important: a different branch name is required at this point)
4. add/copy files for JS dom submission
5. git add, commit, push
6. open a new PR

**Comment by AndriiZahumnyi** [comment]
> Let's re-try:
> 
> 1. `git checkout main`
> 2. Check if there are any files from JS Dom task. If there are any then halt and tell me, there shouldn't be any. We'd need then to normalize your repo first.
> 3. `git pull upstream`
> 4. `git branch -b js-dom-task` (important: a different branch name is required at this point)
> 5. add/copy files for JS dom submission
> 6. git add, commit, push
> 7. open a new PR

Ok.
Thank you.
I thought about it, a lot - 7 or better 107 circles of Git HELL!!))). Until understand..
It was one of variants with new branch that I already had and delete this PR.

**Comment by OleksiyRudenko** [comment]
You will master it.
> Was mich nicht umbringt, macht mich stärker. (c) Friedrich Gitzsche

**Pull request closed without merging**
