### PR TITLE
Finished Hooli-style-popup task

### PR DESCRIPTION
**Pull request by AsyaYeromina**
### HTML-CSS Popup

[Demo](https://asyayeromina.github.io/kottans-task_html-css-popup/) |
[Code base](https://github.com/AsyaYeromina/kottans-task_html-css-popup)

The code is submitted in a dedicated feature branch.
Please, review.

### CODE REVIEW

**Review by madmaxWMFU — CHANGES_REQUESTED** [review]
As for me it's always good!

Fix a couple of [HTML validator](https://validator.w3.org/nu/?doc=https%3A%2F%2Fasyayeromina.github.io%2Fkottans-task_html-css-popup%2F) errors.

**Review by miroslav-kolomiets — CHANGES_REQUESTED** [review]
Look good! But before merge - please fix validation errors.

**Comment by AsyaYeromina** [comment]
Thanks for review. Is everything ok now?

**Review by madmaxWMFU — APPROVED** [review]
LGTM👍🏼

**Review by miroslav-kolomiets — APPROVED** [review]
Good job! Keep going!)

**Pull request merged**
