### PR TITLE
Dom api task

### PR DESCRIPTION
**Pull request by SophiaPylypchuk**
_Complete the form below and remove this line._

### task name

[Demo](https://sophiapylypchuk.github.io/kottans-frontend/) |
[Code base](https://github.com/SophiaPylypchuk/kottans-frontend)

The code is submitted in a dedicated feature branch.
Please, review.

### CODE REVIEW

**Comment by madmaxWMFU** [comment]
Hi @SophiaPylypchuk !
Your links are not working. Please fix it.

**Comment by SophiaPylypchuk** [comment]
Hi,
Could you please help me.
I don't know what link should be there and what I'm missing.

Best regards,
Sophia Pylypchuk

ср, 21 жовт. 2020 р., 18:55 користувач Maksym Yasenovyi <
notifications@github.com> пише:

**Comment by SophiaPylypchuk** [comment]
> Hi @SophiaPylypchuk !
> Your links are not working. Please fix it.

Hi, could you please tell me what should be in that links?

**Comment by madmaxWMFU** [comment]
You can push the project in your own repository on Github.
Create [Github Pages](https://docs.github.com/en/free-pro-team@latest/github/working-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site)
After that you have two links:
- first, link to the location of your code
- second, demo link (Github Pages)

**Comment by OleksiyRudenko** [comment]
It is expected that you submit your code as a result of the assignment completion as per [instructions](https://github.com/kottans/frontend-2021-homeworks/blob/main/README.md).

If you need support on this please seek for help in the telegram chat.

This PR introduces changes to another contrbutor's code. Please avoid this as we do not want others' contributions get changed in any way.

image

Closing this PR for the reasons above.

**Comment by OleksiyRudenko** [comment]
@SophiaPylypchuk , from your [course diary](https://github.com/SophiaPylypchuk/kottans-frontend#my-progress-rocket) you are yet to complete modules preceding DOM API task. Those would make you well prepared for this assignment. If you need any help ont his please shout out for support in the course chat in telegram

**Comment by SophiaPylypchuk** [comment]
> @SophiaPylypchuk , from your [course diary](https://github.com/SophiaPylypchuk/kottans-frontend#my-progress-rocket) you are yet to complete modules preceding DOM API task. Those would make you well prepared for this assignment. If you need any help ont his please shout out for support in the course chat in telegram

Sorry, I lost a bit.
I changed the links above. What should i do next? 

Modules preceding DOM API task, You mean this task  ----- https://github.com/SophiaPylypchuk/frontend-2021-homeworks
I had problems with the last task on that list :
-make pull-request from your repository to this repository via GitHub web-interface

**Pull request closed without merging**
