### PR TITLE
Populate world

### PR DESCRIPTION
**Pull request by Evgeniy241984**
### Building a Tiny JS World 

[Demo](https://evgeniy241984.github.io/a-tiny-JS-world/) |
[Code base](https://github.com/Evgeniy241984/Evgeniy241984.github.io/blob/master/a-tiny-JS-world/index.js)

The code is submitted in a dedicated feature branch.
Please, review.

### CODE REVIEW

**Comment by madmaxWMFU** [comment]
Delete space between symbols `]` and `(`.

**Comment by Evgeniy241984** [comment]
> Delete space between symbols `]` and `(` in links.

Deleted Already!

**Comment by OleksiyRudenko** [comment]
@Evgeniy241984 your PR contains code from your other projects. No good.
Why happened and how to fix? [Read this](https://gist.github.com/OleksiyRudenko/8b3ddb664308de0634b53c525e551d8b).

Also this task requires to have only the js file submitted. `index.html`, IDE settings etc are not required to review the code.
Please fix.

**Comment by Evgeniy241984** [comment]
> @Evgeniy241984 your PR contains code from your other projects (js-dom). No good.
> Why happened and how to fix? [Read this](https://gist.github.com/OleksiyRudenko/8b3ddb664308de0634b53c525e551d8b).
> 
> Also this task requires to have only the js file submitted. `index.html`, IDE settings, `README.md` etc are not required to review the code.
> Please fix.

I Read it several times.
Sorry, but at this stage of my GIT experience i cant fix by myself!

**Comment by OleksiyRudenko** [comment]
@Evgeniy241984 you can see what files are submitted with this PR browsing thourgh the **Files changed** tab.
image
Check if this is what you wanted to submit (unlikely).
To solve the issue with js-dom files following the link 'Read this' above.

Once done or if you have any further questions feel free pinging me.

**Comment by Evgeniy241984** [comment]
Cant Fix issues that appear with 2nd branch and extrafiles! 
Better will open new pull request!

**Pull request closed without merging**
