### PR TITLE
OOP exercise

### PR DESCRIPTION
**Pull request by AnnaStoyano**
### OOP Exercise

[Demo](https://annastoyano.github.io/a-tiny-JS-world/index) |
[Code base](https://github.com/AnnaStoyano/a-tiny-JS-world/)

Please, review.

### CODE REVIEW

**Comment by OleksiyRudenko** [comment]
@AnnaStoyano thank you for your submission.
Your PR contains files/commits that you most likely didn't intend to have here.
image
Please fix.

**Comment by AnnaStoyano** [comment]
Should I remove this branch and create new without this file?

**Comment by OleksiyRudenko** [comment]
Excessive files deletion should work. Be although careful at to what you're deleting.

**Comment by OleksiyRudenko** [comment]
It is good to check with `git status` what's gonna be commited before adding files with `git add .`

**Comment by AnnaStoyano** [comment]
> Excessive files deletion should work. Be although careful at to what you're deleting.
image
This file doesn`t have delete property(

**Comment by OleksiyRudenko** [comment]
`rm -rf .github/React` should have worked

**Pull request closed without merging**
